name: obsobject
description: >-
  An observable/computed object can notify value changed to observers that listen on it
  Built-in validation with support for localize and extends.
version: 1.0.6
homepage: https://github.com/hientrung/dart-observable
repository: https://github.com/hientrung/dart-observable
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:

dev_dependencies:
  test: ^1.14.7
  #effective_dart: ^1.2.0
  #pedantic: ^1.9.0
