name: obsobject
description: >-
  An observable/computed object can notify value changed to observers that listen on it
  Built-in validation with support for localize and extends.
version: 1.2.2
homepage: https://github.com/hientrung/dart-observable
repository: https://github.com/hientrung/dart-observable
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:

dev_dependencies:
  lints: ^1.0.1
  test: ^1.19.3
