name: obsobject
description: >-
  An observable/computed object can notify value changed to observers that listen on it
  Built-in validation with support for localize and extends.
version: 1.1.0
homepage: https://github.com/hientrung/dart-observable
repository: https://github.com/hientrung/dart-observable
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:

dev_dependencies:
  test: ^1.16.8
  effective_dart: ^1.3.1
  #pedantic: ^1.11.0
